SELECT P.PRODUCT_ID, P.PRODUCT_NAME, sum(O.AMOUNT * P.PRICE) 'TOTAL_SALES'
from FOOD_ORDER as O
inner join FOOD_PRODUCT as P
on P.PRODUCT_ID = O.PRODUCT_ID
WHERE DATE_FORMAT(O.PRODUCE_DATE, '%m') = '05'
group by PRODUCT_ID
order by TOTAL_SALES desc, P.PRODUCT_ID asc